### PR TITLE
Add support to serialize document to oscal

### PR DESCRIPTION
**Pull request by abunashir**
This commit adds support to transformed the `Coradoc::Document` to `Oscal` document. As an initial step, it builds a hash structure that was proposed by `Oscal`, and then use the default `yaml` library to convert that to yaml.

This covers the top level `metadata` and `groups` attributes, along with controls in the document. For each control, it also goes into the clauses and then list out the contents or different parts.

The parsing is still missing the followings:

- List items in the content blocks
- Table and their rows and columns
- Nested structure for each sub-content

### CODE REVIEW

**Comment by abunashir** [comment]
Hey @ronaldtse - This PR includes parsing most of the elements, and here is an [example output of the test doc](https://gist.github.com/abunashir/4cecadb317590988cf74dc21ad5a0261). Could you please have a look?

**Comment by ronaldtse** [comment]
@abunashir found a bug:
https://gist.github.com/abunashir/4cecadb317590988cf74dc21ad5a0261#file-oscal-yml-L51

Should be prose, not prop. Prop is for properties.

**Comment by abunashir** [comment]
Thanks @ronaldtse, I will update that. I'm also going through the Oscal doc, and here are couple of questions I came across.

- From the example oscal seems to orgranize stuff in groups, groups and then last elements as
  contorlls. Any is there any clear definitions when to put things in groups and when to choose
  controls? - https://github.com/usnistgov/oscal-content/blob/main/examples/catalog/yaml/basic-catalog.yaml#L21
  
- In the oscal documentation they seems to list the list and other large content block as it is
  under each part. Do we also need to follow that for our case - https://github.com/usnistgov/oscal-content/blob/main/examples/catalog/yaml/basic-catalog.yaml#L86

Let me know if we should adopt that output based on those specification

**Comment by ronaldtse** [comment]
> * From the example oscal seems to orgranize stuff in groups, groups and then last elements as
>   contorlls. Any is there any clear definitions when to put things in groups and when to choose
>   controls? - https://github.com/usnistgov/oscal-content/blob/main/examples/catalog/yaml/basic-catalog.yaml#L21

I think this is correct. The "group" is a grouping that does not contain text.

When a content group (`===...` block) does not contain content, then it should be encoded as a "group".

> * In the oscal documentation they seems to list the list and other large content block as it is
>   under each part. Do we also need to follow that for our case - https://github.com/usnistgov/oscal-content/blob/main/examples/catalog/yaml/basic-catalog.yaml#L86

This is sloppy work and I consider this wrong. There should never be lists INSIDE a prose block.

**Comment by ronaldtse** [comment]
@abunashir when can we merge this? Thanks.

**Comment by abunashir** [comment]
> @abunashir when can we merge this? Thanks.

Couple of small changes and then I think we can merge this one :)

**Comment by abunashir** [comment]
> > * From the example oscal seems to orgranize stuff in groups, groups and then last elements as
> >   contorlls. Any is there any clear definitions when to put things in groups and when to choose
> >   controls? - https://github.com/usnistgov/oscal-content/blob/main/examples/catalog/yaml/basic-catalog.yaml#L21
> 
> I think this is correct. The "group" is a grouping that does not contain text.
> 
> When a content group (`===...` block) does not contain content, then it should be encoded as a "group".

Make sense for the group, but it also seems to group them as controls in some cases where the group doesn't have content but parts?  Do we also need to consider that?


> > * In the oscal documentation they seems to list the list and other large content block as it is
> >   under each part. Do we also need to follow that for our case - https://github.com/usnistgov/oscal-content/blob/main/examples/catalog/yaml/basic-catalog.yaml#L86
> 
> This is sloppy work and I consider this wrong. There should never be lists INSIDE a prose block.

I agree, I will separate those as parts and list item then :)

**Pull request merged**
